### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by SimplyNoni**
Fixes a bunch of issues:

- Remove unnecessary packages
- getRankFromName() now uses .toLowerCase()
- The /setrank endpoint now uses getRankFromName()
- The lua script now uses HttpService:JSONEncode() so the request body is properly formatted
- The !shout command no longer has `user: user` in the request body

### CODE REVIEW

**Review by yogurtsyum — APPROVED** [review]
LGTM

**Comment by yogurtsyum** [comment]
Thanks for the pull request!

**Comment by yogurtsyum** [comment]
One more question actually (this pr has been reverted in the mean time): why do you remove the body parser?

**Comment by SimplyNoni** [comment]
It's depreciated since it's built into express now.

**Comment by yogurtsyum** [comment]
Oh, I didn't see you used express.json() on line 33. Thanks for the pull request!

**Pull request merged**
